name: flutter_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.9
  shared_preferences: ^2.2.3
  http: ^1.2.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  u_credit_card: ^1.3.1
  molten_navigationbar_flutter: ^1.0.1
  flutter_stripe: ^10.2.0
  youtube_player_flutter: ^9.0.1
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/house2.jpg
    - assets/images/
    - assets/house.jpg
    - assets/icon.png
    - assets/logo-Black.png
    - assets/pxfuel.jpg



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./assets/icon_and.png"